/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FetchMoviesRouteImport } from './routes/fetch-movies'
import { Route as IndexRouteImport } from './routes/index'

const FetchMoviesRoute = FetchMoviesRouteImport.update({
  id: '/fetch-movies',
  path: '/fetch-movies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fetch-movies': typeof FetchMoviesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fetch-movies': typeof FetchMoviesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fetch-movies': typeof FetchMoviesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fetch-movies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fetch-movies'
  id: '__root__' | '/' | '/fetch-movies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FetchMoviesRoute: typeof FetchMoviesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fetch-movies': {
      id: '/fetch-movies'
      path: '/fetch-movies'
      fullPath: '/fetch-movies'
      preLoaderRoute: typeof FetchMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FetchMoviesRoute: FetchMoviesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
